version: '2'
services:
  web:
    image: node:latest
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    env_file: .env
    ports:
      - "80:8000"
    depends_on:
      - mongo
    command: npm run docker
  mongo:
    image: mongo
    command: mongod